baseURL = "https://mikeriverso.com/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Mike Riverso · Landing Page"

_merge = "none"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Mike Riverso"
  # email does still work but is deprecated.
  # use [params.contact.email] instead.
  #email = "john.doe@example.com"
  description = "Landing Page"
  bio = "Geek, of various sorts.  \nTechnology, games, sci-fi, etc."
  avatar = "img/MikeRiverso-Headshot.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    # the default fontawesome style in simple key-value pairs is "fab", i.e. brand icons
    instagram = "https://instagram.com/mikeriverso"
    twitter = "https://twitter.com/MikeRiverso"
    
    # You may use (inline) tables for more versatility
    # This allows sorting and even more icons.
    # Just make sure not to mix key-value pairs, inline tables and tables,
    # although keeping keeping this order is ok.
    # See https://toml.io/en/v1.0.0 for details
    #[params.contact.1] # key names are sorted lexicographically
     # name = "hiking club" # may be omitted. defaults to key name
     # icon = "globe" # may be omitted. defaults to key name
     # style = "fas" # may be omitted. default = "fas"
     # link = "https://local-hiking.club"
    [params.contact.email]
      name = "email" # may be omitted. defaults to key name
      icon = "envelope" # may be omitted. defaults to key name
      style = "fas" # may be omitted. default = "fas"
      link = "mailto:mike.riverso@gmail.com"
    [params.contact.mastodon]
      style = "fab" # may be omitted. default = "fas"
      link = "https://mastodon.social/@MikeRiverso"
      # By default rel="me" is not set
      # For some services, it makes sense to set it though.
      # This is the case for Mastodon (and Github) if you link back from these services.
      # See
      # https://microformats.org/wiki/rel-me and
      # https://docs.joinmastodon.org/user/profile/#verification
      # for more information.
      # This defaults to false to cover the case of not having control over the linked site.
      rel-me = true
      
